### ISSUE TITLE
Catch exception thrown when attempting to delete an account that does not exist

### ISSUE THREAD

**Issue by chartjes** [mozilla/pytest-fxa#9]
I have a test where I need to explicitly delete an FxA account instead of waiting for pytest-fxa to delete the account during the teardown step.

If I do the following command when using the `fxa_account` and `fxa_client` fixtures:

`fxa_client.destroy_account(fxa_account.email, fxa_account.password)`

it throws an exception during the teardown step. Speaking with @davehunt he suggested a patch to stop throwing an exception when attempting to delete an account that does not exist.

**Comment by davehunt** [comment]
This is addressed by #10
